## 1. 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

In [1]:
# Import module
import numpy as np

In [2]:
print(np.zeros((2, 3)), "-> Values in array are being given as zero.")
print("")
print(np.empty((2, 3)), "-> Values in array do not need to be given in advance, and values are close to zero.")

[[0. 0. 0.]
 [0. 0. 0.]] -> Values in array are being given as zero.

[[0. 0. 0.]
 [0. 0. 0.]] -> Values in array do not need to be given in advance, and values are close to zero.


## 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

In [3]:
a = np.random.rand(2, 3)*100
print(a.round())

[[89. 57. 32.]
 [48. 43. 88.]]


## 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [4]:
# Example
m = 50
n = 80
a = np.random.rand(2, 3) * (n-m) + m
print(a.round())

[[67. 78. 57.]
 [67. 75. 73.]]
