## Import module

In [1]:
# Import
import numpy as np

print(np) # <module 'numpy' from '.../numpy/__init__.py'>
print(np.__version__) # 1.20.1

<module 'numpy' from 'C:\\Users\\acer\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
1.16.5


## Found NumPy array

In [17]:
# range()
for i in range(0, 6):
    print(i, end=" ")
print("")

for i in range(0, 6, 2):
    print(i, end=" ")

0 1 2 3 4 5 
0 2 4 

In [20]:
# np.arange()
print(np.arange(6))
print(np.arange(6.0))
print(np.arange(0, 6, 2))

[0 1 2 3 4 5]
[0. 1. 2. 3. 4. 5.]
[0 2 4]


In [33]:
# linspace() -> Evenly distributed
print(np.linspace(1, 10, num=10))
print("")

print(np.linspace(1, 10, num=10, retstep=True))
print("")

print(np.linspace(1, 10, num=50, endpoint=False))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

[1.   1.18 1.36 1.54 1.72 1.9  2.08 2.26 2.44 2.62 2.8  2.98 3.16 3.34
 3.52 3.7  3.88 4.06 4.24 4.42 4.6  4.78 4.96 5.14 5.32 5.5  5.68 5.86
 6.04 6.22 6.4  6.58 6.76 6.94 7.12 7.3  7.48 7.66 7.84 8.02 8.2  8.38
 8.56 8.74 8.92 9.1  9.28 9.46 9.64 9.82]


## NdArray

In [42]:
# Found a matrix of 3x5
array_1 = np.arange(15).reshape(3, 5)
print(array_1)
print("")

# Attributes
print("1:", type(array_1))
print("2:", array_1.ndim)
print("3:", array_1.shape)
print("4:", array_1.size)
print("5:", array_1.dtype) # Data type
print("6:", array_1.itemsize)
print("7:", array_1.data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

1: <class 'numpy.ndarray'>
2: 2
3: (3, 5)
4: 15
5: int32
6: 4
7: <memory at 0x0000026A0C0154A8>


## Transform array to list

In [46]:
# Only change one level per time
print(list(array_1))

# Change multiple levels at a time
print(array_1.tolist())

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
