In [27]:
# import module
import numpy as np

# Basic info
array_1 = np.arange(15).reshape(3, 5)
print(array_1)
print(array_1.dtype)
print(array_1.itemsize)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
int32
4


## Data type

In [32]:
# Use in numpy
print(array_1.dtype == 'int32')
print(array_1.dtype is 'int32')
print(array_1.dtype is np.int32)

True
False
False


In [33]:
# Use in normal data type
print(array_1.dtype == 'int32')
print(array_1.dtype == np.int32)
print(array_1.dtype is np.dtype('int32'))

True
True
True
