## Array calculation (Same dimension)

In [1]:
# Import module
import numpy as np

# Calculation
a = np.array([20,30,40,50])
b = np.arange(0, 4)

print("a - 2 =", a - 2)
print("a / 10 =", a / 10)
print("a + b =", a + b)
print("a * b =", a * b)

a - 2 = [18 28 38 48]
a / 10 = [2. 3. 4. 5.]
a + b = [20 31 42 53]
a * b = [  0  30  80 150]


## Array calculation (different dimension)

In [2]:
# Calculation
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[2, 1]])

print(a)
print("")
print(b)
print("")
print(a + b)

[[1 2]
 [3 4]
 [5 6]]

[[2 1]]

[[3 3]
 [5 5]
 [7 7]]


## Array calculation (matrix)

In [3]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[5.], [7.]])

# Transpose(A)
print("1:", a.transpose())

# A^(-1)
print("2:", np.linalg.inv(a))

# Determinant
print("3:", np.linalg.det(a))

# Sum of diagonal matrix
print("4:", np.trace(a))

# Ax = b
x = np.linalg.solve(a, b)
print("5:", x)
print("6:", np.dot(a,x))


1: [[1. 3.]
 [2. 4.]]
2: [[-2.   1. ]
 [ 1.5 -0.5]]
3: -2.0000000000000004
4: 5.0
5: [[-3.]
 [ 4.]]
6: [[5.]
 [7.]]


In [4]:
# Power
print(np.power(a, 2))
print("")

# Sqrt
print(np.sqrt(a))
print("")

# Euler's number(e) & exponential function(e^(x))
print(np.e)
print(np.exp(4))
print(np.exp(np.arange(5)))

[[ 1.  4.]
 [ 9. 16.]]

[[1.         1.41421356]
 [1.73205081 2.        ]]

2.718281828459045
54.598150033144236
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [5]:
# Log
# log3(9)
print(np.log(9)/np.log(3))
print(np.log10(a))

2.0
[[0.         0.30103   ]
 [0.47712125 0.60205999]]


In [6]:
c = np.array([[1, -2], [4, -3]])

print(np.abs(c)) # Absolute
print(np.fabs(c)) # Can not deal with complex

[[1 2]
 [4 3]]
[[1. 2.]
 [4. 3.]]
