## Universal function

In [1]:
import numpy as np 

a = np.array([3, 6, 8, 3, 5])
b = np.array([22, 77, 4, 56, 1])

# Statistics
print("Sum(a):", a.sum()) # print(np.sum(a)) = print(sum(a))
print("Max(a)", a.max())
print("Min(a):", a.min())
print("Std(a):", np.std(a))
print("Var(a):", np.var(a))
print("Mean(a):", np.mean(a))
print("Average(a):", np.average(a))
print("Qercentile3(a):", np.quantile(a, 0.75))
print("")

# Return not nan value
print("Nanmax(b):", np.nanmax(b))
print("Nanmin(b):", np.nanmin(b))
print("Nanstd(b):", np.nanstd(b))
print("Nanvar(b):", np.nanvar(b))
print("Nanmean(b):", np.nanmean(b))
print("Nanmedian(b):", np.nanmedian(b))
print("Nanquantile3(b):", np.nanquantile(b, 0.75))
print("")

# Compare two arrays
print("Fmax:", np.fmax(a, b))
print("Fmin:", np.fmin(a, b))
print("Cov:", np.cov(a, b))
print("Coefficient:", np.corrcoef(a, b))
print("Cross-correlation:", np.correlate(a, b))

Sum(a): 25
Max(a) 8
Min(a): 3
Std(a): 1.8973665961010275
Var(a): 3.6
Mean(a): 5.0
Average(a): 5.0
Qercentile3(a): 6.0

Nanmax(b): 77
Nanmin(b): 1
Nanstd(b): 29.819456735494025
Nanvar(b): 889.2
Nanmean(b): 32.0
Nanmedian(b): 22.0
Nanquantile3(b): 56.0

Fmax: [22 77  8 56  5]
Fmin: [3 6 4 3 1]
Cov: [[   4.5   -16.75]
 [ -16.75 1111.5 ]]
Coefficient: [[ 1.         -0.23683933]
 [-0.23683933  1.        ]]
Cross-correlation: [733]


## Multi-dimension array

In [2]:
c = np.arange(12).reshape(3, 4)

print("Sum:", c.sum())
print("Sum(column):", c.sum(axis = 0))
print("Sum(row):", c.sum(axis = 1))

Sum: 66
Sum(column): [12 15 18 21]
Sum(row): [ 6 22 38]


## Sort array

In [3]:
# Search array with different algorithm
print("Sort(b):", np.sort(b))
print("Sort(b):", b.sort(kind = "HeapSort"))
print(b)
print("Sort(b):", np.sort(b, kind = "QuickSort"))
print("SortIndex(b):", np.argsort(b))

Sort(b): [ 1  4 22 56 77]
Sort(b): None
[ 1  4 22 56 77]
Sort(b): [ 1  4 22 56 77]
SortIndex(b): [0 1 2 3 4]


## Search sort

In [4]:
# Search position
print("Search(b):", np.searchsorted(b, 56))
print("SearchIndex(b):", np.searchsorted(b, [2, 0, 89, 3]))

Search(b): 3
SearchIndex(b): [1 0 5 1]


In [5]:
# Return index of max
print("ArrayMax(b):", np.argmax(b))
print("ArrayMax(b):", b.argmax())

# return index of min
print("ArrayMin(b):", np.argmin(b))
print("ArrayMin(b):", b.argmin())

ArrayMax(b): 4
ArrayMax(b): 4
ArrayMin(b): 0
ArrayMin(b): 0


In [6]:
# Condition
np.where(c < 6) # c[0, 0], c[0, 1], c[0, 2]...c[1, 1]

(array([0, 0, 0, 0, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 0, 1], dtype=int64))

In [7]:
# Condition
print(np.where(c != 0))
print(np.nonzero(c))

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))
(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


## Array shape

In [8]:
# Reshape
print(c)
print("")

print(c.reshape(2, 6))
print("")

print(c.resize(4, 3))
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

None
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
# Multi-dimension array to one-dimension array
print(c.ravel())
print(c.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [10]:
# Concatenate
print(np.concatenate((a, b), axis = 0))
print(np.sort(np.concatenate((a, b), axis = 0)))

[ 3  6  8  3  5  1  4 22 56 77]
[ 1  3  3  4  5  6  8 22 56 77]


In [11]:
d = np.arange(10, 22).reshape(4, 3)

# Merge array
print(np.stack((c, d), axis=0))
print("----------")
print(np.stack((c, d), axis=1))
print("----------")
print(np.vstack((c, d)).reshape(3, 8)) # Row
print("----------")
print(np.hstack((c, d)).reshape(3, 8)) # Column

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]
  [19 20 21]]]
----------
[[[ 0  1  2]
  [10 11 12]]

 [[ 3  4  5]
  [13 14 15]]

 [[ 6  7  8]
  [16 17 18]]

 [[ 9 10 11]
  [19 20 21]]]
----------
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 10 11 12 13]
 [14 15 16 17 18 19 20 21]]
----------
[[ 0  1  2 10 11 12  3  4]
 [ 5 13 14 15  6  7  8 16]
 [17 18  9 10 11 19 20 21]]


In [12]:
e = np.hstack((c, d)).reshape(6, 4)
e

array([[ 0,  1,  2, 10],
       [11, 12,  3,  4],
       [ 5, 13, 14, 15],
       [ 6,  7,  8, 16],
       [17, 18,  9, 10],
       [11, 19, 20, 21]])

In [13]:
# Split row
print(np.split(e, 3))
print("----------")

# Split row
print(np.vsplit(e, 2))
print("----------")

# Split column
print(np.hsplit(e, 2))
print("----------")

# Split array
print(np.array_split(e, 5))

[array([[ 0,  1,  2, 10],
       [11, 12,  3,  4]]), array([[ 5, 13, 14, 15],
       [ 6,  7,  8, 16]]), array([[17, 18,  9, 10],
       [11, 19, 20, 21]])]
----------
[array([[ 0,  1,  2, 10],
       [11, 12,  3,  4],
       [ 5, 13, 14, 15]]), array([[ 6,  7,  8, 16],
       [17, 18,  9, 10],
       [11, 19, 20, 21]])]
----------
[array([[ 0,  1],
       [11, 12],
       [ 5, 13],
       [ 6,  7],
       [17, 18],
       [11, 19]]), array([[ 2, 10],
       [ 3,  4],
       [14, 15],
       [ 8, 16],
       [ 9, 10],
       [20, 21]])]
----------
[array([[ 0,  1,  2, 10],
       [11, 12,  3,  4]]), array([[ 5, 13, 14, 15]]), array([[ 6,  7,  8, 16]]), array([[17, 18,  9, 10]]), array([[11, 19, 20, 21]])]
