## Extract values in array

In [1]:
import numpy as np 

a = np.array([1, 2, 3])
print(a[:])
print(a[:2])
print(a[:-1])
print(a[-3:])

[1 2 3]
[1 2]
[1 2]
[1 2 3]


In [2]:
b = np.arange(6, dtype = int).reshape(3, 2)

print(b[:3, 1])
print("")
print(b.strides) # One row has 2 ints, and each int has 4 digits.
print("")

for row in b:
    print(row)

print("")

for i in b.flat:
    print(i)

[1 3 5]

(8, 4)

[0 1]
[2 3]
[4 5]

0
1
2
3
4
5


## Iterative object

In [3]:
# Change to vector
for i in np.nditer(b):
    print(i, end = " ")
print("")

for j in np.nditer(b, order = "C"):
    print(j, end = " ")
print("")

for z in np.nditer(b, order = "F"):
    print(z, end = " ")

0 1 2 3 4 5 
0 1 2 3 4 5 
0 2 4 1 3 5 