In [1]:
# Import module
import numpy as np

# Value
print("1:", np.array([1, 2, 3.0]))
print("2:", np.array([1, 2, 3], dtype = complex))

# Dict
dict_1 = {0: 123, 1: 456}
print("3:", np.array(dict_1))

# Dict to array
print("4:", np.array(list(dict_1.items())))

1: [1. 2. 3.]
2: [1.+0.j 2.+0.j 3.+0.j]
3: {0: 123, 1: 456}
4: [[  0 123]
 [  1 456]]


## Create array with all same vlaues

In [2]:
# All zero values
print(np.zeros((2, 3)))
print("")

# All one values
print(np.ones((2, 3)))
print("")

# All values by arranged
print(np.full((2, 3), 9))
print("")

# Random values
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[9 9 9]
 [9 9 9]]

[[1. 1. 1.]
 [1. 1. 1.]]


## Create array with certain values

In [3]:
# Fixed range
print(np.arange(10, 30, 3))

# Fixed elements
print(np.linspace(0, 5, 5))

# Fixed ratio
print(np.logspace(0, 3, 4)) # np.logspace(10^start, 10^end, elements)

[10 13 16 19 22 25 28]
[0.   1.25 2.5  3.75 5.  ]
[   1.   10.  100. 1000.]


## Random values

In [4]:
# Normal distribution random values
normal = np.random.randn(2, 3)
print(normal)
print("")

# Random values
random = np.random.random((3, 2))
print(random)
print("")

# Integer random values
integers = np.random.randint(0, 10, size=(2,4))
print(integers)

[[-0.32222287  0.96200478 -1.67652204]
 [ 0.86455797  2.33076423  1.00025346]]

[[0.39131656 0.6770728 ]
 [0.8493269  0.34386723]
 [0.2152861  0.62283891]]

[[1 8 2 5]
 [2 2 5 5]]


## Structured Arrays

In [8]:
# Dict to np.dtype()
dict_1 = {'names':('Name', 'num1', 'num2', 'True'), 'formats':((np.str_, 5), np.int32, int, 'U4')}
dict_1 = np.dtype(dict_1)
dict_1

dtype([('Name', '<U5'), ('num1', '<i4'), ('num2', '<i4'), ('True', '<U4')])

In [9]:
# Read data to dict
b = np.genfromtxt("D:/Data Analysis/GitHub/ML100Days/Handout/Day_003.txt", delimiter=',', dtype=dt)
b

array([('Jay', 1, 2, ' Yes'), ('James', 3, 4, ' No'),
       ('Joe', 5, 6, ' Yes')],
      dtype=[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i4'), ('True', '<U4')])

In [10]:
# Fetch elements
print(b[0])
print(b['Name'])
print(b[1]['True'])
print(b[b['num2'] >= 3]['Name'])

# Create zero array
c = np.zeros((1, 3), dtype=dict_1)
print(c)

# Input values
name = ['Chloe', 'Charlotte', 'Clara']
num_1 = [11, 12, 13]
num_2 = [14, 15, 16]
check = ['Y', 'Y', 'N']

c['Name'] = name
c['num1'] = num_1
c['num2'] = num_2
c['True'] = check
print(c)

('Jay', 1, 2, ' Yes')
['Jay' 'James' 'Joe']
 No
['James' 'Joe']
[[('', 0, 0, '') ('', 0, 0, '') ('', 0, 0, '')]]
[[('Chloe', 11, 14, 'Y') ('Charl', 12, 15, 'Y') ('Clara', 13, 16, 'N')]]


## RecordArray

In [11]:
c_rec = c.view(np.recarray)
c_rec

rec.array([[('Chloe', 11, 14, 'Y'), ('Charl', 12, 15, 'Y'),
            ('Clara', 13, 16, 'N')]],
          dtype=[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i4'), ('True', '<U4')])

In [12]:
# Fetch elements
c_rec.Name

array([['Chloe', 'Charl', 'Clara']], dtype='<U5')